apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convex-backend-ingress
  labels:
    app: ingress
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ required "ingress.backend.host must be set" .Values.ingress.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-convex-backend"
                port:
                  number: 3210
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.backend.host }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convex-site-ingress
  labels:
    app: ingress
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ required "ingress.site.host must be set" .Values.ingress.site.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-convex-backend"
                port:
                  number: 3211
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.site.host }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convex-dashboard-ingress
  labels:
    app: ingress
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ required "ingress.dashboard.host must be set" .Values.ingress.dashboard.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-convex-dashboard"
                port:
                  number: 6791
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.dashboard.host }}
  {{- end }}
